name: train-and-report
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Train the model"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py 
          
          # Add text
          echo "## Metrics" > report.md
          cat metrics.txt >> report.md
          
          # Add pictures
          echo "## Data viz" >> report.md
          echo "### Feature importance" >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          echo "### Residuals" >> report.md
          cml-publish residuals.png --md >> report.md
          
          # Send the report!
          cml-send-comment report.md
          
